# The URL the site will be built for
base_url = "https://shannmu.github.io"
title = "山木"
description = "编程笔记、日常记录和个人思考。"
default_language = "zh"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anemone"

[languages.en]
title = "shanmu"
description = "Programming notes, daily records, and personal reflections."

[extra]
# Put all your custom variables here
list_pages = true
default_theme = "light"
author = "shanmu"
display_author = true

header_nav = [
  { path = "/", name_zh = "/首页/", name_en = "/home/" },
  { path = "/computer-tech", name_zh = "/计算机技术/", name_en = "/computer tech/" },
  { path = "/daily-life", name_zh = "/日常生活/", name_en = "/daily life/" },
  { path = "/about", name_zh = "/关于/", name_en = "/about/" },
]

[extra.giscus]
enabled = true
repo = "shannmu/shannmu.github.io"
repo_id = "R_kgDOL-msKA"
category = "Announcements"
category_id = "DIC_kwDOL-msKM4C7Lz8"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "preferred_color_scheme"
loading = "lazy"
